"""
Cognitive Database Agent - SQL Query Validator and Rate Limiter
================================================================
Validates SQL queries generated by the agent against a strict blocklist,
detects statement stacking, verifies subquery depth, and enforces role-based rate limits.
"""

import logging
import re
from time import time
from typing import Dict, List, Tuple

from fastapi import HTTPException, status

logger = logging.getLogger(__name__)

# Rate limit thresholds (queries per minute)
RATE_LIMITS = {"viewer": 30, "manager": 60, "admin": 120}

# In-memory history for rate limiting: {role: [timestamps]}
_rate_limit_history: Dict[str, List[float]] = {"viewer": [], "manager": [], "admin": []}


class QueryValidator:
    """
    SQL Query Validator and Rate Limiter.
    Ensures generated queries are safe, single-statement, and within rate limits.
    """

    # Blocked keywords in queries to prevent destructive operations or privilege escalation
    BLOCKLIST = [
        "DROP",
        "TRUNCATE",
        "ALTER",
        "CREATE",
        "GRANT",
        "REVOKE",
        "COPY",
        "EXECUTE",
        "SET ROLE",
        "SET LOCAL ROLE",
    ]

    @staticmethod
    def strip_comments(query: str) -> str:
        """
        Strip SQL single-line and multi-line comments.
        """
        # Remove multi-line /* ... */ comments
        query = re.sub(r"/\*.*?\*/", "", query, flags=re.DOTALL)
        # Remove single-line -- comments
        query = re.sub(r"--.*$", "", query, flags=re.MULTILINE)
        return query.strip()

    @staticmethod
    def has_stacked_statements(query: str) -> bool:
        """
        Detect stacked statements (multiple queries separated by semicolon).
        """
        parts = query.split(";")
        non_empty = [p.strip() for p in parts if p.strip()]
        return len(non_empty) > 1

    @staticmethod
    def check_subquery_depth(query: str) -> int:
        """
        Determine the maximum nesting depth of subqueries (parentheses containing SELECT).

        This tracks nesting levels to prevent complex, recursive queries that can cause
        database denial of service or stack overflows in the query planner.
        """
        query_upper: str = query.upper()
        max_depth: int = 0
        current_depth: int = 0
        stack: List[bool] = []

        for i, char in enumerate(query_upper):
            if char == "(":
                # Check if this parenthesis starts a subquery
                remainder: str = query_upper[i + 1 :].strip()
                if remainder.startswith("SELECT"):
                    current_depth += 1
                    max_depth = max(max_depth, current_depth)
                    stack.append(True)
                else:
                    stack.append(False)
            elif char == ")":
                if stack:
                    is_select: bool = stack.pop()
                    if is_select:
                        current_depth -= 1

        return max_depth

    @classmethod
    def validate(cls, query: str, allowed_type: str) -> Tuple[bool, str]:
        """
        Validate a query against blocklist, statement stacking, and subquery depth.

        Args:
            query: The raw SQL query string.
            allowed_type: The expected SQL verb (e.g. 'SELECT', 'INSERT', 'UPDATE', 'DELETE').

        Returns:
            Tuple[bool, str]: (is_valid, rejection_reason)
        """
        if not query:
            return False, "Query is empty"

        # 1. Strip comments
        clean_query = cls.strip_comments(query)
        if not clean_query:
            return False, "Query contains only comments"

        # 2. Check query starts with allowed verb
        clean_upper = clean_query.upper()
        if not clean_upper.startswith(allowed_type.upper()):
            return False, f"Query must start with {allowed_type.upper()}"

        # 3. Check blocklist keywords
        for keyword in cls.BLOCKLIST:
            # Match keywords as whole words to avoid issues with column/table names (e.g., alter_ego)
            pattern = r"\b" + re.escape(keyword) + r"\b"
            if re.search(pattern, clean_upper):
                return False, f"Query contains blocked keyword: {keyword}"

        # 4. Check for stacked statements
        if cls.has_stacked_statements(clean_query):
            return False, "Stacked queries (semicolon separation) are blocked"

        # 5. Check subquery depth (limit to 3)
        depth = cls.check_subquery_depth(clean_query)
        if depth > 3:
            return False, f"Subquery nesting depth {depth} exceeds the limit of 3"

        return True, ""

    @staticmethod
    def enforce_rate_limit(role: str):
        """
        Enforce rate limits per user role.
        Raises HTTP 429 when rate limit is exceeded.
        """
        role = role.lower()
        if role not in RATE_LIMITS:
            # Default to viewer limit if role is unknown
            role = "viewer"

        now = time()
        one_minute_ago = now - 60

        global _rate_limit_history
        # Prune old timestamps
        _rate_limit_history[role] = [
            t for t in _rate_limit_history[role] if t > one_minute_ago
        ]

        # Verify limit
        limit = RATE_LIMITS[role]
        if len(_rate_limit_history[role]) >= limit:
            logger.warning(f"Rate limit exceeded for role: {role} (Limit: {limit}/min)")
            raise HTTPException(
                status_code=status.HTTP_429_TOO_MANY_REQUESTS,
                detail=f"Rate limit exceeded for role '{role}'. Maximum {limit} queries per minute.",
            )

        # Log current request
        _rate_limit_history[role].append(now)
